import { NextResponse, type NextRequest } from "next/server";
import { getSession } from "@/lib/auth/session";
import { getRequestTimeZone } from "@/lib/tz-server";
import { prisma } from "@/lib/db";
import {
  autoGenerateDiary,
  type ClientExif,
} from "@/lib/diary/auto-generate";
import {
  MAX_AI_INPUT_CONTENT_LENGTH,
  clientExifSchema,
  dateKeySchema,
  moodKeySchema,
} from "@/lib/diary/schemas";
import { findDiaryForDate } from "@/lib/diary/queries";
import { appendToDay } from "@/lib/diary/day-merge";
import { MAX_IMAGES_PER_REQUEST } from "@/lib/diary/limits";
import { STORAGE_FULL_MSG } from "@/lib/storage/quota";
import { todayKeyInZone } from "@/lib/tz";
import { unauthorized } from "@/lib/auth/unauthorized";
import { aiFailureStatus } from "@/lib/http/ai-status";
import { withJsonErrors } from "@/lib/http/with-json-errors";

// multipart 필드:
//   photo  — File 0~N장 (상한은 일기당 10장 고정, autoGenerateDiary가 판정, getAll)
//   exifs  — JSON string (배열, photos와 길이 일치)
//   text   — 사용자 메모 (선택)


// 재정리(preview-regenerate·[id]/regenerate)와 같은 상한을 쓴다. 여기만 2000이면
// 긴 메모를 쓴 사용자가 최초 정리에서 막히는데, 정작 재정리는 통과하는 모순이 생긴다.
// 작성 화면 textarea에는 maxLength가 없어 실제로 도달 가능한 경로였다.
const MAX_TEXT_LENGTH = MAX_AI_INPUT_CONTENT_LENGTH;

async function handlePOST(req: NextRequest) {
  const session = await getSession();
  if (!session) {
    return unauthorized();
  }

  // 캐릭터 조회 (AI cap 계산에 사용. 사진 상한은 티어와 무관해졌다 — limits.ts)
  const character = await prisma.character.findUnique({
    where: { userId: session.userId },
    select: { subscriptionStatus: true, plan: true },
  });
  if (!character) {
    return NextResponse.json(
      { error: "캐릭터를 찾을 수 없어요" },
      { status: 404 },
    );
  }
  let formData: FormData;
  try {
    formData = await req.formData();
  } catch {
    return NextResponse.json({ error: "잘못된 요청 형식" }, { status: 400 });
  }

  // 사진 수집
  const photos: File[] = [];
  for (const f of formData.getAll("photo")) {
    if (f instanceof File && f.size > 0) photos.push(f);
  }
  // 장수 상한 판정은 autoGenerateDiary가 담당한다(AI 입력 비용 가드).

  // EXIF 파싱·검증 (photos와 1:1 매핑)
  let exifs: ClientExif[] = [];
  const exifsRaw = formData.get("exifs");
  if (typeof exifsRaw === "string" && exifsRaw.length > 0) {
    try {
      const parsed = JSON.parse(exifsRaw);
      if (!Array.isArray(parsed)) throw new Error("not an array");
      exifs = parsed.map((item) => clientExifSchema.parse(item));
    } catch {
      return NextResponse.json(
        { error: "EXIF 데이터 형식이 잘못되었습니다" },
        { status: 400 },
      );
    }
  }
  if (exifs.length !== photos.length) {
    return NextResponse.json(
      { error: "사진과 EXIF 개수가 일치해야 합니다" },
      { status: 400 },
    );
  }

  // 텍스트
  const textRaw = formData.get("text");
  const text =
    typeof textRaw === "string" && textRaw.trim().length > 0
      ? textRaw.trim()
      : undefined;
  if (text && text.length > MAX_TEXT_LENGTH) {
    return NextResponse.json(
      { error: `메모는 ${MAX_TEXT_LENGTH}자 이내여야 합니다` },
      { status: 400 },
    );
  }

  const timeZone = await getRequestTimeZone();

  // 하루에 일기는 하나다(점검 M5). 정리할 날짜에 일기가 이미 있으면(메이와 나눈 조각이
  // 모인 일기 포함) 검토 화면에서 새 일기를 만들지 않고 그 일기에 합친다. 정리는 화면이
  // 이어서 따로 부른다 — 직접 쓴 글과 그날 조각이 한 일기에서 엮인다(day-merge.ts).
  const dateRaw = formData.get("date");
  if (typeof dateRaw === "string" && dateRaw.length > 0) {
    const dk = dateKeySchema.safeParse(dateRaw);
    if (!dk.success) {
      return NextResponse.json({ error: "날짜 형식이 올바르지 않아요" }, { status: 400 });
    }
    if (dk.data > todayKeyInZone(timeZone)) {
      return NextResponse.json({ error: "미래 날짜로는 쓸 수 없어요" }, { status: 400 });
    }
    // 목록에 안 보이는 빈 일기만 있는 날은 사용자 눈엔 빈 날이다 — 평소처럼 검토 화면으로
    // 보내고, 저장할 때 그 빈 일기에 채운다(createDiaryAction).
    const sameDay = await findDiaryForDate(session.userId, dk.data);
    if (sameDay && !sameDay.empty) {
      if (photos.length > MAX_IMAGES_PER_REQUEST) {
        return NextResponse.json(
          { error: `사진은 한 번에 ${MAX_IMAGES_PER_REQUEST}장까지 올릴 수 있어요` },
          { status: 400 },
        );
      }
      const mood = moodKeySchema.safeParse(formData.get("mood"));
      const merged = await appendToDay({
        userId: session.userId,
        diaryId: sameDay.id,
        dateKey: dk.data,
        photos,
        exifs,
        text,
        mood: mood.success ? mood.data : undefined,
      });
      if (!merged.ok) {
        return NextResponse.json(
          { error: merged.error },
          { status: merged.error === STORAGE_FULL_MSG ? 400 : 503 },
        );
      }
      return NextResponse.json({ merged: true, diaryId: merged.diaryId });
    }
  }

  // 오케스트레이션 실행
  const result = await autoGenerateDiary({
    timeZone,
    userId: session.userId,
    subscriptionStatus: character.subscriptionStatus,
    plan: character.plan,
    photos,
    exifs,
    text,
  });

  if (!result.ok) {
    // 상태 기준은 모든 AI 라우트 공통(ai-status.ts). 공간 부족은 400, 모델 실패는 503.
    const status = aiFailureStatus(result);
    return NextResponse.json(
      {
        error: result.error,
        capExhausted: result.capExhausted ?? false,
        storageFull: result.storageFull ?? false,
      },
      { status },
    );
  }

  return NextResponse.json({
    draft: result.draft,
    storagePaths: result.storagePaths,
    exifs: result.exifs,
    mode: result.mode,
  });
}

// 처리 못 한 예외도 JSON으로 — 화면이 res.json()에서 터지지 않게(점검 M8).
export const POST = withJsonErrors(handlePOST);
