import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { getSession } from "@/lib/auth/session";
import { maxImagesForStatus } from "@/lib/character/utils";
import { prisma } from "@/lib/db";
import {
  autoGenerateDiary,
  type ClientExif,
} from "@/lib/diary/auto-generate";

// multipart 필드:
//   photo  — File 0~N장 (상한은 구독별: ACTIVE 10 / 그 외 5, getAll)
//   exifs  — JSON string (배열, photos와 길이 일치)
//   text   — 사용자 메모 (선택, max 2000자)

const exifItemSchema = z.object({
  takenAt: z.string().nullable(),
  lat: z.number().nullable(),
  lng: z.number().nullable(),
});

const MAX_TEXT_LENGTH = 2000;

export async function POST(req: NextRequest) {
  const session = await getSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // 캐릭터 조회 (구독 상태 → 사진 상한 + AI cap 계산에 사용)
  const character = await prisma.character.findUnique({
    where: { userId: session.userId },
    select: { subscriptionStatus: true },
  });
  if (!character) {
    return NextResponse.json(
      { error: "캐릭터를 찾을 수 없어요" },
      { status: 404 },
    );
  }
  const maxPhotos = maxImagesForStatus(character.subscriptionStatus);

  let formData: FormData;
  try {
    formData = await req.formData();
  } catch {
    return NextResponse.json({ error: "잘못된 요청 형식" }, { status: 400 });
  }

  // 사진 수집
  const photos: File[] = [];
  for (const f of formData.getAll("photo")) {
    if (f instanceof File && f.size > 0) photos.push(f);
  }
  if (photos.length > maxPhotos) {
    return NextResponse.json(
      { error: `사진은 최대 ${maxPhotos}장까지 첨부할 수 있어요` },
      { status: 400 },
    );
  }

  // EXIF 파싱·검증 (photos와 1:1 매핑)
  let exifs: ClientExif[] = [];
  const exifsRaw = formData.get("exifs");
  if (typeof exifsRaw === "string" && exifsRaw.length > 0) {
    try {
      const parsed = JSON.parse(exifsRaw);
      if (!Array.isArray(parsed)) throw new Error("not an array");
      exifs = parsed.map((item) => exifItemSchema.parse(item));
    } catch {
      return NextResponse.json(
        { error: "EXIF 데이터 형식이 잘못되었습니다" },
        { status: 400 },
      );
    }
  }
  if (exifs.length !== photos.length) {
    return NextResponse.json(
      { error: "사진과 EXIF 개수가 일치해야 합니다" },
      { status: 400 },
    );
  }

  // 텍스트
  const textRaw = formData.get("text");
  const text =
    typeof textRaw === "string" && textRaw.trim().length > 0
      ? textRaw.trim()
      : undefined;
  if (text && text.length > MAX_TEXT_LENGTH) {
    return NextResponse.json(
      { error: `메모는 ${MAX_TEXT_LENGTH}자 이내여야 합니다` },
      { status: 400 },
    );
  }

  // 오케스트레이션 실행
  const result = await autoGenerateDiary({
    userId: session.userId,
    subscriptionStatus: character.subscriptionStatus,
    photos,
    exifs,
    text,
  });

  if (!result.ok) {
    const status = result.capExhausted ? 429 : 502;
    return NextResponse.json(
      {
        error: result.error,
        capExhausted: result.capExhausted ?? false,
      },
      { status },
    );
  }

  return NextResponse.json({
    draft: result.draft,
    storagePaths: result.storagePaths,
    exifs: result.exifs,
    mode: result.mode,
  });
}
