import "server-only";
import type { SubscriptionStatus, SubscriptionPlan } from "@prisma/client";
import { prisma } from "@/lib/db";
import { saveImage } from "@/lib/storage";
import { assertStorageQuota, STORAGE_FULL_MSG } from "@/lib/storage/quota";
import {
  generateDiary,
  type DiaryGenerationMode,
  type DiaryGenerationOutput,
} from "@/lib/ai/gemini";
import { checkAndIncrement } from "@/lib/ai/usage";
import { buildExifSummary } from "./exif-summary";
import { MAX_IMAGES_PER_DIARY } from "./limits";

// 클라이언트가 EXIF를 추출해 multipart의 별도 필드로 보낸다 (압축 시 EXIF 손실 회피).
export type ClientExif = {
  takenAt: string | null; // ISO 8601
  lat: number | null;
  lng: number | null;
};

export type AutoGenerateInput = {
  userId: string;
  subscriptionStatus: SubscriptionStatus;
  plan: SubscriptionPlan;
  photos: File[]; // 상한은 구독별(ACTIVE 10 / 그 외 5), 이미 1024px로 클라 측 압축됨
  exifs: ClientExif[];
  text?: string;
};

export type AutoGenerateResult =
  | {
      ok: true;
      draft: DiaryGenerationOutput;
      storagePaths: string[];
      exifs: ClientExif[];
      mode: DiaryGenerationMode;
    }
  | {
      ok: false;
      error: string;
      capExhausted?: boolean;
      storageFull?: boolean; // 스토리지 쿼터 초과 — caller가 4xx로 구분해 응답
      uploadedToCleanup?: string[]; // Gemini 실패 시 garbage collector(V2)가 정리
    };

/**
 * F1 자동 생성 오케스트레이션 (NEW-4).
 *   - cap 검증 → Storage 업로드 → Gemini 호출 → draft 반환
 *   - DB 저장은 X (검토 게이트가 사용자 승인 후 createDiary 호출)
 *   - 부분 실패 정책: 사진 업로드 도중 실패 시 즉시 에러 반환 (이미 업로드 파일은 V2 GC)
 *   - Gemini 실패 시 storagePath들을 uploadedToCleanup으로 caller에 반환
 */
export async function autoGenerateDiary(
  input: AutoGenerateInput,
): Promise<AutoGenerateResult> {
  // 모드 결정
  const hasPhotos = input.photos.length > 0;
  const hasText = !!input.text?.trim();
  if (!hasPhotos && !hasText) {
    return { ok: false, error: "사진 또는 텍스트가 필요합니다" };
  }
  // 티어별 장수 상한은 폐기(용량 쿼터가 대체). 개수 상한 자체는 티어와 무관한
  // 고정값으로 남는다 — 여기 사진은 전부 Gemini 입력이라 장수가 곧 호출 비용이다.
  if (input.photos.length > MAX_IMAGES_PER_DIARY) {
    return {
      ok: false,
      error: `사진은 일기 한 건에 ${MAX_IMAGES_PER_DIARY}장까지 넣을 수 있어요`,
    };
  }
  const mode: DiaryGenerationMode =
    hasPhotos && hasText ? "C" : hasPhotos ? "A" : "B";

  // 스토리지 쿼터 사전검증 — AI 횟수를 쓰기 전에 판정한다(막힐 거면 크레딧을 소모하지 않는다).
  // 여기선 업로드만 막고 카운터는 건드리지 않는다: 검토를 이탈하면 고아가 되므로
  // 계수는 createDiaryAction의 확정 저장에서만 일어난다.
  const photoBytes = input.photos.reduce((sum, p) => sum + p.size, 0);
  if (photoBytes > 0) {
    const quota = await assertStorageQuota(input.userId, photoBytes);
    if (!quota.ok) return { ok: false, error: STORAGE_FULL_MSG, storageFull: true };
  }

  // cap 검증·증분
  const cap = await checkAndIncrement(input.userId, input.subscriptionStatus, input.plan);
  if (!cap.allowed) {
    return {
      ok: false,
      error: "오늘 AI 사용 횟수를 모두 사용했어요. 내일 다시 만나요.",
      capExhausted: true,
    };
  }

  // 페르소나 조회 (베타엔 기본값 row가 가입 시 자동 생성)
  const persona = await prisma.userPersona.findUnique({
    where: { userId: input.userId },
    select: {
      presetKey: true,
      tone: true,
      formality: true,
      sentenceLength: true,
    },
  });

  // Storage 업로드 (병렬). 부분 실패 시 이미 업로드된 정리는 V2 GC.
  // sizeBytes는 여기서 기록하지 않는다 — 초안 단계라 DiaryImage insert 자체가 없고,
  // 사용자가 검토를 이탈하면 고아가 된다(GC 대상). 크기 기록·쿼터 카운터는
  // createDiaryAction의 확정 저장(preuploaded 경로)에서만 일어난다.
  const storagePaths: string[] = [];
  for (const photo of input.photos) {
    try {
      const path = await saveImage(photo, input.userId);
      storagePaths.push(path);
    } catch (e) {
      return {
        ok: false,
        error: `이미지 업로드 실패: ${e instanceof Error ? e.message : "unknown"}`,
        uploadedToCleanup: storagePaths,
      };
    }
  }

  // 사진 → base64 (Gemini 멀티모달)
  const photoData = await Promise.all(
    input.photos.map(async (photo) => ({
      mimeType: photo.type,
      base64Data: Buffer.from(await photo.arrayBuffer()).toString("base64"),
    })),
  );

  // Gemini 호출
  try {
    const draft = await generateDiary({
      mode,
      photos: photoData.length > 0 ? photoData : undefined,
      text: input.text,
      persona: persona ?? undefined,
      exifSummary: buildExifSummary(input.exifs),
    });

    return { ok: true, draft, storagePaths, exifs: input.exifs, mode };
  } catch (e) {
    return {
      ok: false,
      error: e instanceof Error ? e.message : "AI 생성 실패",
      uploadedToCleanup: storagePaths,
    };
  }
}
