import "server-only";
import type { SubscriptionStatus, SubscriptionPlan } from "@prisma/client";
import { prisma } from "@/lib/db";
import { maxImagesForStatus } from "@/lib/character/utils";
import { saveImage } from "@/lib/storage";
import {
  generateDiary,
  type DiaryGenerationMode,
  type DiaryGenerationOutput,
} from "@/lib/ai/gemini";
import { checkAndIncrement } from "@/lib/ai/usage";
import { buildExifSummary } from "./exif-summary";

// 클라이언트가 EXIF를 추출해 multipart의 별도 필드로 보낸다 (압축 시 EXIF 손실 회피).
export type ClientExif = {
  takenAt: string | null; // ISO 8601
  lat: number | null;
  lng: number | null;
};

export type AutoGenerateInput = {
  userId: string;
  subscriptionStatus: SubscriptionStatus;
  plan: SubscriptionPlan;
  photos: File[]; // 상한은 구독별(ACTIVE 10 / 그 외 5), 이미 1024px로 클라 측 압축됨
  exifs: ClientExif[];
  text?: string;
};

export type AutoGenerateResult =
  | {
      ok: true;
      draft: DiaryGenerationOutput;
      storagePaths: string[];
      exifs: ClientExif[];
      mode: DiaryGenerationMode;
    }
  | {
      ok: false;
      error: string;
      capExhausted?: boolean;
      uploadedToCleanup?: string[]; // Gemini 실패 시 garbage collector(V2)가 정리
    };

/**
 * F1 자동 생성 오케스트레이션 (NEW-4).
 *   - cap 검증 → Storage 업로드 → Gemini 호출 → draft 반환
 *   - DB 저장은 X (검토 게이트가 사용자 승인 후 createDiary 호출)
 *   - 부분 실패 정책: 사진 업로드 도중 실패 시 즉시 에러 반환 (이미 업로드 파일은 V2 GC)
 *   - Gemini 실패 시 storagePath들을 uploadedToCleanup으로 caller에 반환
 */
export async function autoGenerateDiary(
  input: AutoGenerateInput,
): Promise<AutoGenerateResult> {
  // 모드 결정
  const hasPhotos = input.photos.length > 0;
  const hasText = !!input.text?.trim();
  if (!hasPhotos && !hasText) {
    return { ok: false, error: "사진 또는 텍스트가 필요합니다" };
  }
  const maxImages = maxImagesForStatus(input.subscriptionStatus);
  if (input.photos.length > maxImages) {
    return {
      ok: false,
      error: `사진은 최대 ${maxImages}장까지 첨부할 수 있어요`,
    };
  }
  const mode: DiaryGenerationMode =
    hasPhotos && hasText ? "C" : hasPhotos ? "A" : "B";

  // cap 검증·증분
  const cap = await checkAndIncrement(input.userId, input.subscriptionStatus, input.plan);
  if (!cap.allowed) {
    return {
      ok: false,
      error: "오늘 AI 사용 횟수를 모두 사용했어요. 내일 다시 만나요.",
      capExhausted: true,
    };
  }

  // 페르소나 조회 (베타엔 기본값 row가 가입 시 자동 생성)
  const persona = await prisma.userPersona.findUnique({
    where: { userId: input.userId },
    select: {
      presetKey: true,
      tone: true,
      formality: true,
      sentenceLength: true,
    },
  });

  // Storage 업로드 (병렬). 부분 실패 시 이미 업로드된 정리는 V2 GC.
  const storagePaths: string[] = [];
  for (const photo of input.photos) {
    try {
      const path = await saveImage(photo, input.userId);
      storagePaths.push(path);
    } catch (e) {
      return {
        ok: false,
        error: `이미지 업로드 실패: ${e instanceof Error ? e.message : "unknown"}`,
        uploadedToCleanup: storagePaths,
      };
    }
  }

  // 사진 → base64 (Gemini 멀티모달)
  const photoData = await Promise.all(
    input.photos.map(async (photo) => ({
      mimeType: photo.type,
      base64Data: Buffer.from(await photo.arrayBuffer()).toString("base64"),
    })),
  );

  // Gemini 호출
  try {
    const draft = await generateDiary({
      mode,
      photos: photoData.length > 0 ? photoData : undefined,
      text: input.text,
      persona: persona ?? undefined,
      exifSummary: buildExifSummary(input.exifs),
    });

    return { ok: true, draft, storagePaths, exifs: input.exifs, mode };
  } catch (e) {
    return {
      ok: false,
      error: e instanceof Error ? e.message : "AI 생성 실패",
      uploadedToCleanup: storagePaths,
    };
  }
}
